apiVersion: v1
kind: Pod
metadata: 
  name: myprobe-pod
  labels:
    app: prob-yellow-pod 
spec:
  containers:
    - name: my-yellow-container 
      image: longflew/ingress:YELLOWPAGE 
      ports:
        - containerPort: 80
      startupProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        failureThreshold: 3
        successThreshold: 1
      livenessProbe:
        exec:
          command:
            - touch
            - 1.txt
        initialDelaySeconds: 10
        failureThreshold: 3
        successThreshold: 1
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 10
        failureThreshold: 3
        successThreshold: 1
        
        
        