apiVersion: v1
kind: Pod
metadata:
  name : myclusterpod
  labels:
    app: blue-app
spec: 
  containers:
    - name: myblue-containers
      image: longflew/ingress:BLUEPAGE
      ports:
        - containerPort: 80